# Generated by Django 3.0.7 on 2020-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/home/roman/Desktop/rp-portfolio/projects/static/img'),
        ),
    ]
