# Generated by Django 3.0.7 on 2020-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200729_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='GitHub',
            field=models.CharField(default='Sorry, i will add GitHub link as soon as possible', max_length=255),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(related_name='Project', to='projects.Technology'),
        ),
    ]
