# Generated by Django 3.0.7 on 2020-07-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.FilePathField(path='my_certificates/static/img', recursive=True),
        ),
    ]
