# Generated by Django 3.0.7 on 2020-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_certificates', '0003_auto_20200728_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(upload_to='my_certificates/static/img'),
        ),
    ]
