# Generated by Django 3.0.7 on 2020-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_certificates', '0005_auto_20200729_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='image_uploud',
        ),
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
