# Generated by Django 3.0.7 on 2020-06-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200630_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Last_modified',
            new_name='last_modified',
        ),
    ]
